### ISSUE TITLE
Not pulling diff with existing open connection to Juniper

### ISSUE THREAD

**Issue by Trilogie** [nornir-automation/nornir_napalm#14]
Hello,

I ran into an issue where if I open a connection with a task, and do not close that connection, if I run another task (specifically in this case a dry run of a configuration push), I do not receive a diff back, even though I see the configuration being pushed correctly and rolled back.

Snippet of what I am running:
`facts = task.run(task=napalm_get, getters=["get_facts"])`

This opens the napalm connection to my device, and it stays open when my code gets to this portion:

`deploy_configuration = task.run(task=napalm_configure,
                                            dry_run=True,
                                            configuration=task.host["full_template"],
                                            replace=True)`

Now when I am doing a debug, I see that the connection is still open under nornir, but never receive the diff back. Once I add a close connection after the "get_facts" line, it all works cleanly. Ideally I would like to use the same ssh connection because while this works on single devices, when I am running it against several devices, I will be opening a lot of unnecessary ssh sessions.

Line I am adding to correct:
`facts = task.run(task=napalm_get, getters=["get_facts"])`
`task.host.close_connection("napalm")`

Thanks.

**Comment by dbarrosop** [comment]
Can you share the full code that triggers the issue?

**Comment by ktbyers** [comment]
Closing as no response (after request for additional info).
