### ISSUE TITLE
Passing enable secret to NAPALM IOS driver via inventory and directly via ConnectOptions

### ISSUE THREAD

**Issue by gaffar10** [nornir-automation/nornir_napalm#17]
Dears,

I am using Napalm on the Nornir framework and the script works fine if I configure the privilege level 15 password on the Cisco Device. However, on the production devices, by default it goes to the User EXEC(Switch>) mode, then I have to manually type "enable" to go into the Privileged EXEC mode(Switch#).

Is there any alternate option, to pass the secret password similar to the get.pass method?

Since I use the Nornir framework, I pass the 'secret' argument in groups.yaml file, however, it doesn't work. Is it possible to define the "secret" argument in an encrypted format rather than defining it in cleartext?

cisco_group:
    platform: "ios"
    connection_options:
      napalm:
        extras:
        optional_args:
          fast_cli: False
          secret: cisco

Thanks in Advance

**Comment by ktbyers** [comment]
@gaffar10 Sure, it is Python so you can use environment variables, getpass(), or some encrypted data.

But with the encrypted data, you would have to write it yourself there is nothing built into the SimpleInventory for encrypted YAML data. The Python cryptography library is pretty straightforward for encrypting/decryption data, however.


Regards, Kirk

**Comment by gaffar10** [comment]
Dear @ktbyers, Thank you so much for your swift response. I know how to pass the username and password, using the input or getpass method. However, I am struggling to find the syntax for enable/secret password. 

The below syntax works well to pass UN/PWD. 
username = input("Username:")
password = getpass.getpass()

nr.inventory.defaults.username = username
nr.inventory.defaults.password = password

However, the same is not working for secret.
**secret = getpass.getpass() OR  secret = input("enable:")

nr.inventory.defaults.secret = secret**

I also try to add, the secret argument in defaults.yaml and in the groups.yaml, but I am getting the below error message.

      **napalm:
        extras:
        optional_args:
          fast_cli: False
          secret: cisco**

++++++++++++Result++++++++++
Username:cisco
Password: 
enable:cisco
Traceback (most recent call last):
  File "test7.py", line 14, in <module>
    nr.inventory.defaults.secret = secret
AttributeError: 'Defaults' object has no attribute 'secret'

Thanks

**Comment by ktbyers** [comment]
It needs to be in `connection_options` format so for `groups.yaml` it would be similar to the following:

```yaml
my_group:
  platform: nxos
  connection_options:
    napalm:
      extras:
        optional_args:
          fast_cli: False
          secret: my_secret
```

**Comment by gaffar10** [comment]
Dear @ktbyers, Thank you very much for your response again. All the scripts I had was working fine with privilege level 15 password. After I remove the privilege level 15 on the Cisco device, the script stopped working even if I add the secret password on groups.yaml

R1#show run | i user|secret
enable secret 5 $1$cVXx$TKzE24ujrPzJs1oFGUbQ1.
username cisco password 0 cisco
R1#

Attached the basic script + Invenventory files.
[Inventory and scripts.zip](https://github.com/nornir-automation/nornir_napalm/files/7143485/Inventory.and.scripts.zip)

test8.py = Using nornir framework, the credentials are added in groups + host.yaml file
test10.py = Using nornir framework,  the credentials are added in groups + host.yaml file. Used netmiko connection handler + session log to see what is happening in the background.

Thanks,
Gaffar

**Comment by ktbyers** [comment]
From:

https://github.com/nornir-automation/nornir/discussions/720

-------
Can someone please help to provide me the syntax to pass the optional_args, secret?

For example, with input, get. pass, Env variable, GPG encryption method, I was able to pass the username and password successfully.

```python
username = input("Enter Username: ")
password = input("Enter Password: ") OR password = getpass.getpass()
nr.inventory.defaults.username = username
nr.inventory.defaults.password = password
```

However, I don't know the syntax to pass the secret password. I tried with the below options but it doesn't work.

```python
secret = input("Enter Enable Password: ") OR secret = getpass.getpass()

nr.inventory.defaults.secret = secret
nr.inventory.defaults.connection_options.napalm.extras.optional_args.secret = secret
nr.inventory.defaults.connection_options['napalm'] = ConnectionOptions(extras={"optional_args":{"secret":"secret"}})
```

Thanks in advance

**Comment by gaffar10** [comment]
Dear @ktbyers, I am able to run the script by adding the secret password in groups.yaml. I am also able to pass the username and password using the input method, get.pass method, environment variable, and GPG encryption.

But I don't know the syntax to pass the secret password in Nornir. Could you please help me with that? 

Thanks,
Gaffar

**Comment by ktbyers** [comment]
Give me a minute...testing it.

**Comment by ktbyers** [comment]
This second form you have should work properly (I just tested it in my environment):

```
nr.inventory.defaults.connection_options['napalm'] = ConnectionOptions(
    extras={"optional_args":{"secret":"secret"}}
)
```

Make sure, however, you do NOT have connection options defined at either the host or group level. In general, you will probably have less long-term problems by only defining connection options at the group level.

Technically, you can't have `connection_options > extras` at either the host or group level or the most specific one of those will win (or worded different it is not a dictionary merge, it is the most specific dictionary wins).

**Comment by bit-git** [comment]
Hi Kirk, How do I use below with your nornir_set_creds() function? https://github.com/ktbyers/nornir_test/blob/master/nornir_test/nornir_utilities.py 

`
nr.inventory.defaults.connection_options['napalm'] = ConnectionOptions(
    extras={"optional_args":{"secret":"secret"}}
)
`
Could you please share an example? thank you
Regards

**Comment by gaffar10** [comment]
Dear Kirk, Thank you very much for your usual and extended support. Finally, I am able to pass the secret password with the below syntax.

```
secret = getpass.getpass()
nr.inventory.groups['cisco_group'].connection_options['napalm'].extras['optional_args']['secret'] = secret
```
If POSSIBLE please share your sample script and the group.yaml files for the below syntax.  

`nr.inventory.defaults.connection_options['napalm'] = ConnectionOptions(extras={"optional_args":{"secret":"secret"}})`

Thanks again Kirk

**Comment by bit-git** [comment]
Got KeyError: 'napalm' using 
nr.inventory.groups['routers'].connection_options['napalm'].extras['optional_args']['secret'] = secret

**Comment by gaffar10** [comment]
You have to remove the optional arguments "secret" in groups.yaml.

**Comment by gaffar10** [comment]
Attached are the sample script and groups.yaml file.
[Sample.zip](https://github.com/nornir-automation/nornir_napalm/files/7170250/Sample.zip)

**Comment by ktbyers** [comment]
For groups you would set connection options like this:

```python
ios.inventory.groups["ios"].connection_options["napalm"] = ConnectionOptions(
    extras={"optional_args": {"secret": "my_secret"}}
)
```

You could also loop over all the groups in inventory:

```python
for group_obj in ios.inventory.groups.values():
    group_obj.connection_options["napalm"] = ConnectionOptions(
    extras={"optional_args": {"secret": "my_secret"}}
)
```

**Comment by bit-git** [comment]
How can i use this 
`for group_obj in ios.inventory.groups.values():
    group_obj.connection_options["napalm"] = ConnectionOptions(
    extras={"optional_args": {"secret": "my_secret"}}
)`

with 
`def nornir_set_creds(norn, username=None, password=None):
    """Handler so credentials don't need stored in clear in inventory."""
    if not username:
        username = input("Enter username: ")
    if not password:
        password = getpass()

    for host_obj in norn.inventory.hosts.values():
        host_obj.username = username
        host_obj.password = password`

getting - NameError: name 'ConnectionOptions' is not defined

Thanks a lot for your help

**Comment by bit-git** [comment]
Tried this didnt get any code error but doesnt work 

`def nornir_set_creds(norn, username=None, password=None):
    """Handler so credentials don't need stored in clear in inventory."""
    if not username:
        username = input("Enter username: ")
    if not password:
        password = getpass()

    for host_obj in norn.inventory.hosts.values():
        host_obj.username = username
        host_obj.password = password
    
    for group_obj in norn.inventory.groups['routers']:
        group_obj.connection_options["napalm"].extras['optional_args']['secret']  = password
`

**Comment by bit-git** [comment]
got it working - thanks for the help 


    for host in norn.inventory.hosts.keys():
        norn.inventory.hosts[host].connection_options['napalm'].extras['optional_args']['secret'] = password
