### ISSUE TITLE
Bump ruamel.yaml to match latest nornir dependency version requirements

### ISSUE THREAD

**Issue by ryanmerolle** [nornir-automation/nornir_napalm#18]
https://github.com/nornir-automation/nornir_napalm/blob/5f22d3e7ec222faed5111c7083c7b420f9d3e997/poetry.lock#L1219-L1225

vs

https://github.com/nornir-automation/nornir/blob/5cca4a8a579eecbd33c88304da6e451dc92e0922/poetry.lock#L1332-L1337

**Comment by dbarrosop** [comment]
Hi, thanks for reporting this issue. Would you mind describing what is the problem you are trying to solve? In which situation is this a problem for you?

Thanks!
