### ISSUE TITLE
no confirm_commit in napalm_configure

### ISSUE THREAD

**Issue by milan2655** [nornir-automation/nornir_napalm#69]
Hallo!

i'm using _napalm_configure_ with **revert_in** to merge config.

if the **rever_in** timer is set, in the _IOSDriver.commit_config_ method there is no _device.confirm_commit()_.

every time system will rollback to the backup config.

[        if revert_in_min is None:](https://github.com/napalm-automation/napalm/blob/29c5ea0ac5db3b95c98c32e2035edfcda7a3d6f8/napalm/ios/ios.py#L606)

there is nothing to do if the **revert_in_min** is True!

**Comment by ktbyers** [comment]
https://github.com/nornir-automation/nornir_napalm/blob/master/nornir_napalm/plugins/tasks/napalm_confirm_commit.py

**Comment by milan2655** [comment]
**napalm_confirm_commit** task need to be called after **commit_config** to check pending commits and finally to confirm_commit.

is that correct? 

without napalm_confirm_commit, change will never be committed! of course if _revert timer_ is used. without revert everything should be ok. 

thx!

**Comment by ktbyers** [comment]
Yes, if you are going to use `revert_in` with `napalm_configure`, then you need to use `napalm_confirm_commit` to actually confirm the commit.
