### ISSUE TITLE
NAPALM 5.0.0 support

### ISSUE THREAD

**Issue by ubaumann** [nornir-automation/nornir_napalm#70]
Yesterday [NAPALM v5.0.0](https://github.com/napalm-automation/napalm/releases/tag/5.0.0) was released.

Can we support versions 4 and 5 in the next version? Users could pin the NAPALM version in the requirements.
Besides dropping Python 3.7, the changes in NAPALM depend on how the user uses the library/tasks, but the interfaces this plugin uses remain the same.

My suggestion would be to:
- Drop Python 3.7 support as well
- change the version-pin to `napalm = "^4|^5"`
- Update the version to 0.5.0

What do you think would be the best solution?

**Comment by ktbyers** [comment]
I would probably vote that we only support NAPALM 5 (i.e. if someone needed to use NAPALM version 4.x, then they could just use a slightly older version of nornir_napalm).

Do you see a strong reason for needing to support both Napalm 4.x and Napalm 5.x @ubaumann ?

**Comment by ubaumann** [comment]
For me, only v5 support would be fine. 
I guess if someone still uses an older version than EOS 4.23, it should be okay to use nornir_napalm 0.4.0

**Comment by dbarrosop** [comment]
My vote goes to napalm 5 only too.

**Comment by ubaumann** [comment]
Great.  I can make a PR for the NAPALM v5 version.  Should I bump the version already to 0.5.0? Or better do the release in a subsequent step?

**Comment by dbarrosop** [comment]
I think releasing is a good idea.

**Comment by ktbyers** [comment]
Release sounds good to me.
